### ISSUE TITLE
Support for loading table per hierarchy types, and types that aren't entities?

### ISSUE THREAD

**Issue by triynko** [moozzyk/CodeFirstFunctions#21]
EF's built in ObjectContext.Translate method, as well as the vanilla ExecuteFunction, ExecuteStoreQuery, etc. all support mapping to complex types, whether they're entities or not.

1. Why does this system require all types to be EDM types?  One the the types my sproc returns is just a plain data set, it's not an entity type. It's just meta data about the other result sets, which are entity types.

2. This system fails to load types that are table per hierarchies, throwing an error saying it can't instantiate an instance of an abstract class. It's supposed to read the discriminator column and construct the appropriate subclass.

It seems like there's just no support anywhere in this system or any of the built-in methods like Translate or ExecuteStoreQuery that are capable of reading a Table-Per-Hierarchy type from a result set.  Is there any known way to do this?  The only thing that seems to work is plain direct queries on the DbSet of the DbContext.

**Comment by moozzyk** [comment]
For the non-EF Core version of EF Code First is built on top of ObjectContext. ObjectContext required CSDL SDL and MSL artifacts to be able to work. These artifacts were Xml files that defined the conceptual model, database layer and mapping between the two. CodeFirst is hiding is building these artifacts from the user's code and then feeds them to the ObjectContext it internally uses. One important thing is that CodeFirst is using only a subset of functionality offered by ObjectContext. The other important thing is that because DbContext is just a wrapper around ObjectContext it cannot provide more functionality than ObjectContext provides.

CodeFirstFunctions is positioned to fill the _CodeFirst is using only a subset of functionality offered by ObjectContext_ gap. Out of the box CodeFirst does not support store functions even though ObjectContext does. By introducing annotations and conventions CodeFirstFunctions is able to build fragments of the model responsible for store functions. Finally, the entire model is loaded into the ObjectContext which has all the information needed to handle store functions.

AFAIR you can bypass all the EF/EDM/artifacts mumbo jumbo by using the `Database.SqlQuery` method. You need to check the documentation but I think you can provide non-Entity type as result and EF will just use a 1:1 mapping between property names and column names. I think `.Translate` did the same thing.

Now we reached the second part (i.e. _DbContext is just a wrapper around ObjectContext it cannot provide more functionality than ObjectContext provides_) which I think should answer your question.
(Disclaimer: It's been a while since I looked at EF internals so forgive if my answer is not 100% accurate.)
Entities and Complex types are part of the EF model which not only contains the shape of the entity but also how properties are mapped to columns in the database (and or vice versa). If you provided a type that EF does not know about it would not know what property a value from a given column should go to.

AFAIR ObjectContext did not support mapping store functions results to hierarchies. I think that the reason for that was that it would be very hard for the user to come up with a resultset that meets all the criteria for a given mapping. 

Closing since this is not anything that can be fixed in CodeFirstFunctions.
