### ISSUE TITLE
The specified method '...' cannot be translated into a LINQ to Entities store expression.

### ISSUE THREAD

**Issue by gfody** [moozzyk/CodeFirstFunctions#30]
I have an inline table-valued function, e.g.:

```sql
create function Thing1(@thing2 int) returns table as return
	select 1 asdf from some_view with (noexpand) where thing2 = @thing2
```

I've exposed it like so:
```C#
[DbFunctionDetails(ResultColumnName="asdf")]
[DbFunction("myRepo", "Thing1")]
public IQueryable<int> Thing1(int thing2) =>
    ((IObjectContextAdapter)this).ObjectContext.CreateQuery<int>("Thing1(@thing2)", new ObjectParameter("thing2", thing2));
```
I can call it by itself no problem, e.g.:

`myRepo.Thing2(3).Dump(); // works fine`

..but when I incorporate it into a query, I get "the specified method cannot be translated into a LINQ to Entities store expression" error. e.g.:

`OtherThing.Where(c => Thing1(c.Id).Any()).Take(1).Dump(); // boom!`

am I doing anything wrong or is this just not supported?

**Comment by moozzyk** [comment]
I think `.Any()`is the problem here. AFAIR `.Any()` in EF forces query to be sent to the database and executed so cannot be translated in the query.

**Comment by gfody** [comment]
When I use `.Any()` with other entities it translates into a `WHERE EXISTS (...` which is what I want here.

Ideally this would generate:
```sql
select * from OtherThing where exists (select * from Thing1(Id))
```

**Comment by moozzyk** [comment]
In general `Any()` will work as you describe. I think your original case is a bit different though because in that case `Any()` does not apply to the table the query is rooted at. You may try asking in the [EF6](https://github.com/aspnet/EntityFramework6) repo if your scenario is supported. CodeFirstFunctions does not translate queries - it only fills missing metadata to enable what EF already could do if the metadata was loaded from edmx.
