### ISSUE TITLE
Select on Table Valued Function is not supported

### ISSUE THREAD

**Issue by CodeTroopers** [moozzyk/CodeFirstFunctions#6]
The select on the result of a table valued function throw an exception 

> Invalid object name

In my examples GetChildrenLocations is a table valued function that return this entity:
```
public class ChildLocation
{
	[Key]
	public int Id{ get; set; }
	public int ParentId { get; set; }
	public int Level { get; set; }
	public string Root { get; set; }

	[ForeignKey("Id")]
	public Location Location { get; set; }

	[ForeignKey("ParentId")]
	public Location Parent { get; set; }
}
```
This work:
`dbContext.Customers.SelectMany(c => dbContext.GetChildrenLocations(c.RootLocationId)).ToList()`
This does not work :
`dbContext.Customers.SelectMany(c => dbContext.GetChildrenLocations(c.RootLocationId)).Select(l => l.Location).ToList()`

**Comment by moozzyk** [comment]
Can you show me how you mapped the TVF and also the full stack trace?

I guess you can work around the issue by doing: `dbContext.Customers.SelectMany(c => dbContext.GetChildrenLocations(c.RootLocationId)).ToList().Select(l => l.Location)`
this will materialize results on the client instead of the database and the Select is just a regular Linq to Objects Select but I think the original query should work as well. I don't have tests for `Select` but I do have [tests for `Where`](https://github.com/moozzyk/CodeFirstFunctions/blob/master/CodeFirstStoreFunctionsTests/E2ETests.cs#L486) which I think would hit the same issue.

**Comment by CodeTroopers** [comment]
```
[DbFunction("EntityDbContext", "GetChildrenLocations")]
public IQueryable<ChildLocation> GetChildrenLocations(int rootId)
{
	return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ChildLocation>(String.Format("[{0}].[GetChildrenLocations](@Root)", this.GetType().Name), new ObjectParameter("Root", rootId));
}
```

**Comment by moozzyk** [comment]
@RealRegatta - can you also post a full stack trace?

**Comment by moozzyk** [comment]
I modified this line: https://github.com/moozzyk/CodeFirstFunctions/blob/1349dea5fea16eab1be2d3841bc3aaf14b8f152e/CodeFirstStoreFunctionsTests/E2ETests.cs#L570 to use `Select` instead of `Where` like this:

```C#
var airports = ctx.GetPassedAirportType(null).Select(a => a.HasValue).ToList();
```
and did not get any exception. SQL sent to the database looked as follows:

```SQL
SELECT 
    CASE WHEN ([Extent1].[Type] IS NOT NULL) THEN cast(1 as bit) ELSE cast(0 as bit) END AS [C1]
    FROM [dbo].[GetPassedAirportType](@AirportType) AS [Extent1]
```

So, what I tried works as expected. Please provide a complete (but simplified) repro. Include the TVF you are trying to call, the model, the context, how you configured the convention and how you are calling the TVF.

**Comment by moozzyk** [comment]
Closing - no followup.
